name: animu_common
description: Shared Code between AngularDart and Flutter for Animu
version: 0.1+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.7
  bloc: ^2.0.0
  equatable: ^1.0.1
  http: ^0.12.0+2
  flutter_secure_storage: ^3.3.1+1
